#!/bin/bash

title="$1"
shift

printf '%s\n' "# ${title}"

for f in "$@" ; do
    name=$(basename ${f})
    imag="![${name}](${f} \"${name}\")"
    printf '%s\n' "## ${name}"
    printf '%s %s %s %s %s\n' "[${imag}](${f})" "[[PDF]](${f%.*}.pdf)" "[[PNG]](${f%.*}.png)" "[[SVG]](${f})" "[[TEX]](${f%.*}.tex)"
done
